number1= input('Enter the length of rectangle: ')
length = int(number1)
number2= input('Enter the breadth of the rectanagle: ')
breadth= int(number2)
perimeter = 2*(length + breadth)
print("perimeter of the rectangle is ", perimeter)